name: Terraform Deployment

on:
  workflow_dispatch:
    inputs:
      workspace:
        description: "Terraform workspace name (development, staging, or production)"
        required: true
        type: choice
        options:
        - development
        - staging
        - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 0.18.2
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Create Terraform workspace
      env:
        TF_WORKSPACE: ${{ inputs.workspace }}
      run: |
        terraform login -no-color -non-interactive -hostname=app.terraform.io -username=${{ secrets.TF_USERNAME }} -password=${{ secrets.TF_API_TOKEN }}
        terraform workspace new ${{ env.TF_WORKSPACE }} || terraform workspace select ${{ env.TF_WORKSPACE }}

    - name: Terraform apply
      env:
        TF_WORKSPACE: ${{ inputs.workspace }}
      run: |
        cd environments/${{ inputs.workspace }}
        terraform init
        terraform workspace select ${{ env.TF_WORKSPACE }}
        terraform plan
        terraform apply -auto-approve

