name: Terraform Deployment

on:
  workflow_dispatch:
    inputs:
      workspace:
        description: "Terraform workspace name (development, staging, or production)"
        required: true
        type: choice
        options:
        - development
        - staging
        - production
      
      instance_type:
          description: "Choose the EC2 instance type"
          required: true
          type: choice
          options:
          - t2.micro
          - t2.nano
      
      instance_count:
         description: "Add the count of the created EC2 instances"
         required: false
         type: string


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Terraform
      uses: hashicorp/setup-terraform@v1
      with:
          terraform_version: 0.14.7
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Checkout code
      uses: actions/checkout@v2
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: setup workspace
      uses: reguengos/terraform-github-workspace-setup-action@master
      with:
          organization: "terraform-rayah"
          workspace: ${{ inputs.workspace }}
          token: ${{ secrets.TF_API_TOKEN }}


    - name: Update variables file
      run: |
          cd enviornments/${{ inputs.workspace }}
          echo "instance_count = \"${{ inputs.instance_count }}\"" >> terraform.tfvars
          echo "ec2_instance_type = \"${{ inputs.instance_type }}\"" >> terraform.tfvars


    - name: Terraform apply
      run: |
      
        cd enviornments/${{ inputs.workspace }}
        terraform init 
        terraform plan -var-file=terraform.tfvars -input=false
        # terraform apply -auto-approve -var-file=terraform.tfvars -input=false
       

